<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>0.0.1</Version>
        <RootNamespace>Stg.Nez</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Nez\Nez.Portable\Nez.FNA.Core.csproj" />
    </ItemGroup>

</Project>
